levels:
  0:
    name: "Level 0"
    material: GRAY_CONCRETE
    bricks_slots:

  1:
    name: "Level 1"
    material: GRAY_CONCRETE
    bricks_slots:
      - 14
      - 42

  2:
    name: "Level 2"
    material: GRAY_CONCRETE
    bricks_slots:
      - 22
      - 24

  3:
    name: "Level 3"
    material: GRAY_CONCRETE
    bricks_slots:
      - 12
      - 14
      - 30
      - 31
      - 33
      - 42

  4:
    name: "Level 4"
    material: GRAY_CONCRETE
    bricks_slots:
      - 6
      - 23
      - 29
      - 40

  5:
    name: "Level 5"
    material: GRAY_CONCRETE
    bricks_slots:
      - 4
      - 5
      - 6
      - 38
      - 39

  6:
    name: "Level 6"
    material: GRAY_CONCRETE
    bricks_slots:
      - 12
      - 21
      - 30

  7:
    name: "Level 7"
    material: GRAY_CONCRETE
    bricks_slots:
      - 4
      - 21
      - 30
      - 41
      - 42

  8:
    name: "Level 8"
    material: GRAY_CONCRETE
    bricks_slots:
      - 2
      - 3
      - 14
      - 21
      - 23
      - 32

game_zone_slots:
  - 2
  - 3
  - 4
  - 5
  - 6
  - 11
  - 12
  - 13
  - 14
  - 15
  - 20
  - 21
  - 22
  - 23
  - 24
  - 29
  - 30
  - 31
  - 32
  - 33
  - 38
  - 39
  - 40
  - 41
  - 42

lvl_items:
  decor:
    BLACK_STAINED_GLASS_PANE:
      name: "&8by: _Degeron_"
      slots:
        - 1
        - 10
        - 19
        - 28
        - 37
        - 7
        - 16
        - 25
        - 34
        - 43

    WHITE_STAINED_GLASS_PANE:
      name: "&8by: _Degeron_"
      slots:
        - 9
        - 17
        - 27
        - 35

  bricks:
    material: RED_STAINED_GLASS_PANE
    name: "&cBrick"

  cursor:
    material: YELLOW_STAINED_GLASS_PANE
    name: "&eCursor"

  well:
    material: LIME_STAINED_GLASS_PANE
    name: "&aWell"

  cancel:
    material: BARRIER
    name: "&cMenu"
    slot: 8

  pointers:
    up:
      material: GOLD_NUGGET
      name: "&e⬆"
      slot: -9

    right:
      material: GOLD_NUGGET
      name: "&e➡"
      slot: 1

    down:
      material: GOLD_NUGGET
      name: "&e⬇"
      slot: 9

    left:
      material: GOLD_NUGGET
      name: "&e⬅"
      slot: -1

menu_items:
  menu_name: "Menu"
  decor:
    BLACK_STAINED_GLASS_PANE:
      name: "&8by: _Degeron_"
      slots:
        - 2
        - 3
        - 4
        - 5
        - 6
        - 10
        - 16
        - 19
        - 25
        - 28
        - 34
        - 38
        - 39
        - 40
        - 41
        - 42

    WHITE_STAINED_GLASS_PANE:
      name: "&8by: _Degeron_"
      slots:
        - 1
        - 7
        - 37
        - 43

  level_slots:
      - 12
      - 13
      - 14
      - 23
      - 22
      - 21
      - 30
      - 31
      - 32